# Generated by Django 4.1.1 on 2023-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nama", models.CharField(max_length=100)),
                ("Alamat", models.CharField(max_length=100)),
                (
                    "Jenis_Alat",
                    models.CharField(
                        choices=[
                            ("Forklift", "Forklift"),
                            ("Crane", "Crane"),
                            ("Gondola", "Gondola"),
                            ("Alat Berat", "Alat Berat"),
                            ("Passenger Hoist", "Passenger Hoist"),
                            ("Conveyor", "Conveyor"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "kelas",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3")], max_length=1
                    ),
                ),
                ("KTP", models.ImageField(null=True, upload_to="ktp/")),
                ("CV", models.FileField(upload_to="cv/")),
                ("Foto", models.ImageField(upload_to="foto/")),
                (
                    "Ijazah",
                    models.CharField(
                        choices=[
                            ("Sekolah Menengah Pertama", "SMP"),
                            ("Sekolah Menengah Atas", "SMA"),
                            ("Diploma I", "D1"),
                            ("Diploma II", "D2"),
                            ("Diploma III", "D3"),
                            ("Diploma IV", "D4"),
                            ("Strata I", "S1"),
                        ],
                        max_length=25,
                    ),
                ),
                ("SuratPernyataan", models.FileField(upload_to="surat_pernyataan/")),
                ("Keterangan_Kerja", models.FileField(upload_to="keterangan_kerja/")),
            ],
        ),
    ]
