# Generated by Django 4.1.1 on 2023-01-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulir",
            name="kelas",
            field=models.CharField(
                choices=[("None", "None"), ("1", "1"), ("2", "2"), ("3", "3")],
                max_length=25,
            ),
        ),
    ]
