# Generated by Django 4.1.1 on 2023-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_formulir_kelas"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulir",
            name="Asal_perusahaan",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
